/* Vmapops WebGIS · Long Ngo · MIT 2026 */
'use strict';
(() => {
 const $ = id => document.getElementById(id);
 const paths={plus:'M12 5v14M5 12h14',locate:'M12 2v4m0 12v4M2 12h4m12 0h4M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',fit:'M4 9V4h5m6 0h5v5m0 6v5h-5m-6 0H4v-5',info:'M12 11v6m0-10v1M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',layers:'m12 3 9 5-9 5-9-5 9-5ZM3 12l9 5 9-5M3 16l9 5 9-5'};
 const icon=name=>'<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[name]+'"/></svg>';
 [['zoom-in','plus'],['locate','locate'],['fullscreen','fit']].forEach(([id,name])=>$(id).innerHTML=icon(name));
 $('import-btn').innerHTML=icon('plus')+' Thêm lớp';document.querySelector('.data-note>span').innerHTML=icon('info');document.querySelector('.summary-icon').innerHTML=icon('layers');
 const KEY = 'vmapops.settings.v2';
 const read = (store,key,fallback) => {try{return JSON.parse(store.getItem(key)) || fallback;}catch{return fallback;}};
 let config = read(localStorage, KEY, {});
 let token = read(sessionStorage, KEY+'.token', '') || config.token || '';
 let toastTimer;
 function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
 if(typeof L==='undefined'){toast('Không tải được thư viện bản đồ. Vui lòng tải lại trang.');return;}
 if(matchMedia('(max-width:800px)').matches)document.body.classList.add('collapsed');
 const map=L.map('map',{zoomControl:false,center:[10.25,105.97],zoom:8});
 L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);
 const layers=[];let base,activeBase='osm',measuring=false,points=[],searchMarker,locationMarker;
 const measureLayer=L.layerGroup().addTo(map);
 const safeText=value=>{const el=document.createElement('span');el.textContent=String(value??'');return el.innerHTML;};
 function url(value,templates=false){const s=value.trim();if(!s)return '';const u=new URL(s);if(u.protocol!=='https:' && !(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('URL phải dùng HTTPS (hoặc localhost để phát triển).');if(u.username||u.password)throw Error('Không đặt tài khoản trong URL.');if(templates && !['{z}','{x}','{y}'].every(t=>s.includes(t)))throw Error('URL XYZ phải chứa đủ {z}, {x}, {y}.');return s;}
 function setBase(kind){if(kind==='custom'&&!config.tileUrl){openSettings();return;}const next=L.tileLayer(kind==='custom'?config.tileUrl:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:kind==='custom'?safeText(config.credit||'Bản đồ riêng'):'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'});let warned=false;next.on('tileerror',()=>{if(!warned){warned=true;toast('Không tải được một số ô bản đồ. Kiểm tra mạng hoặc URL bản đồ nền.');}});if(base)map.removeLayer(base);base=next.addTo(map);activeBase=kind;document.querySelectorAll('[data-base]').forEach(b=>b.classList.toggle('selected',b.dataset.base===kind));}
 function validateGeoJSON(data){if(!data || typeof data!=='object')throw Error('Phản hồi không phải GeoJSON.');const types=['FeatureCollection','Feature','Point','MultiPoint','LineString','MultiLineString','Polygon','MultiPolygon','GeometryCollection'];function check(g){if(!g||!types.includes(g.type))throw Error('Kiểu GeoJSON không hợp lệ.');if(g.type==='FeatureCollection'){if(!Array.isArray(g.features))throw Error('Thiếu danh sách features.');g.features.forEach(f=>{if(f.type!=='Feature')throw Error('Phần tử phải là Feature.');check(f);});}else if(g.type==='Feature'){if(g.geometry)check(g.geometry);}else if(g.type==='GeometryCollection'){if(!Array.isArray(g.geometries))throw Error('Thiếu geometries.');g.geometries.forEach(check);}else{const depths={Point:0,MultiPoint:1,LineString:1,MultiLineString:2,Polygon:2,MultiPolygon:3};function coords(c,d){if(!Array.isArray(c))throw Error('Tọa độ không hợp lệ.');if(d){c.forEach(x=>coords(x,d-1));}else if(c.length<2||!c.every(Number.isFinite)||Math.abs(c[0])>180||Math.abs(c[1])>90)throw Error('GeoJSON cần tọa độ WGS84: kinh độ, vĩ độ.');}coords(g.coordinates,depths[g.type]);}}check(data);return data;}
 function popup(feature,layer){const wrap=document.createElement('div');const title=document.createElement('strong');title.textContent=feature.properties?.name||'Thông tin đối tượng';wrap.append(title);Object.entries(feature.properties||{}).slice(0,30).forEach(([k,v])=>{const row=document.createElement('div');row.style.fontSize='11px';row.textContent=k+': '+(typeof v==='object'?JSON.stringify(v):v);wrap.append(row);});layer.bindPopup(wrap);}
 function addData(data,name,source='file'){validateGeoJSON(data);const color=source==='demo'?'#397859':['#327e91','#9c7440','#825e9e'][layers.length%3];const group=L.geoJSON(data,{style:{color,weight:3,fillOpacity:.15},pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,color:'#fff',weight:2,fillColor:color,fillOpacity:1}),onEachFeature:popup});const entry={name,group,source,visible:true,count:group.getLayers().length};if(source==='api'){layers.filter(x=>x.source==='api').forEach(x=>{map.removeLayer(x.group);layers.splice(layers.indexOf(x),1);});}layers.push(entry);group.addTo(map);renderLayers();return group;}
 function renderLayers(){const list=$('layer-list');list.replaceChildren();layers.forEach(entry=>{const row=document.createElement('div');row.className='layer-row';const top=document.createElement('div');top.className='layer-top';const check=document.createElement('input');check.type='checkbox';check.checked=entry.visible;check.setAttribute('aria-label','Hiển thị '+entry.name);check.onchange=()=>{entry.visible=check.checked;entry.visible?entry.group.addTo(map):map.removeLayer(entry.group);updateStats();};const label=document.createElement('label');label.textContent=entry.name;const sub=document.createElement('small');sub.textContent=entry.count+' đối tượng · '+(entry.source==='demo'?'Minh họa':entry.source==='api'?'API riêng':'GeoJSON');label.append(sub);const fit=document.createElement('button');fit.innerHTML=icon('locate');fit.title='Xem lớp này';fit.onclick=()=>fitGroup(entry.group);const remove=document.createElement('button');remove.textContent='×';remove.title='Xóa lớp';remove.onclick=()=>{map.removeLayer(entry.group);layers.splice(layers.indexOf(entry),1);renderLayers();};top.append(check,label,fit,remove);const opacity=document.createElement('input');opacity.type='range';opacity.min=0;opacity.max=100;opacity.value=100;opacity.setAttribute('aria-label','Độ đậm '+entry.name);opacity.oninput=()=>entry.group.setStyle({opacity:opacity.value/100,fillOpacity:opacity.value/100*(entry.source==='demo'?1:.4)});row.append(top,opacity);list.append(row);});updateStats();}
 function updateStats(){const visible=layers.filter(x=>x.visible);$('feature-count').textContent=visible.reduce((a,x)=>a+x.count,0)+' đối tượng';$('layer-count').textContent=visible.length+' lớp đang hiển thị';}
 function fitGroup(group){const bounds=group.getBounds();if(bounds.isValid())map.fitBounds(bounds,{padding:[45,45],maxZoom:14});else toast('Lớp không có hình học để định vị.');}
 function collapse(){document.body.classList.add('collapsed');map.invalidateSize();}
 $('close-panel').onclick=collapse;$('open-panel').onclick=()=>{document.body.classList.remove('collapsed');map.invalidateSize();};
 ['layers','tools'].forEach(name=>$(name+'-tab').onclick=()=>{['layers','tools'].forEach(n=>{$(n+'-tab').setAttribute('aria-selected',String(n===name));$(n+'-panel').hidden=n!==name;});});
 document.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>setBase(b.dataset.base));
 $('zoom-in').onclick=()=>map.zoomIn();$('zoom-out').onclick=()=>map.zoomOut();$('home').onclick=()=>map.setView([16,107],6);
 $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Trình duyệt không hỗ trợ toàn màn hình.');}};
 $('locate').onclick=()=>{if(!navigator.geolocation){toast('Thiết bị không hỗ trợ định vị.');return;}navigator.geolocation.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];if(locationMarker)map.removeLayer(locationMarker);locationMarker=L.circleMarker(ll,{radius:9,color:'#fff',weight:3,fillColor:'#4285f4',fillOpacity:1}).addTo(map).bindPopup('Vị trí của bạn');map.setView(ll,15);},()=>toast('Chưa lấy được vị trí. Kiểm tra quyền định vị của trình duyệt.'),{timeout:12000});};
 map.on('mousemove',e=>$('coordinates').textContent=`${e.latlng.lat.toFixed(5)}°, ${e.latlng.lng.toFixed(5)}°`);map.on('zoomend',()=>$('zoom-label').textContent='Zoom '+map.getZoom());
 $('fit').onclick=()=>{const g=L.featureGroup(layers.filter(x=>x.visible).map(x=>x.group));fitGroup(g);if(innerWidth<800)collapse();};
 $('measure').onclick=()=>{measuring=!measuring;$('measure').classList.toggle('active',measuring);$('measure-info').hidden=!measuring;map.getContainer().style.cursor=measuring?'crosshair':'';if(measuring&&innerWidth<800)collapse();};
 $('clear-measure').onclick=()=>{points=[];measureLayer.clearLayers();$('measure-info').textContent='Chọn điểm trên bản đồ để đo.';};
 map.on('click',e=>{if(!measuring)return;points.push(e.latlng);measureLayer.clearLayers();L.polyline(points,{color:'#d07c35',weight:3,dashArray:'6 5'}).addTo(measureLayer);points.forEach(p=>L.circleMarker(p,{radius:4,color:'#d07c35'}).addTo(measureLayer));let distance=0;for(let i=1;i<points.length;i++)distance+=points[i-1].distanceTo(points[i]);$('measure-info').textContent=`${points.length} điểm · ${(distance/1000).toFixed(2)} km`;});
 $('import-btn').onclick=()=>$('file-input').click();$('file-input').onchange=async e=>{const files=Array.from(e.target.files);for(const file of files){try{if(file.size>20*1024*1024)throw Error('Vui lòng dùng tệp nhỏ hơn 20 MB.');const g=addData(JSON.parse(await file.text()),file.name);fitGroup(g);toast('Đã thêm '+file.name);if(innerWidth<800)collapse();}catch(err){toast('Không nhập được dữ liệu: '+err.message);}}e.target.value='';};
 function download(data,name){const a=document.createElement('a');const objectURL=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/geo+json'}));a.href=objectURL;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(objectURL),1000);}
 $('export').onclick=()=>{const features=layers.filter(x=>x.visible).flatMap(x=>x.group.toGeoJSON().features);if(!features.length){toast('Chưa có đối tượng để xuất.');return;}download({type:'FeatureCollection',features},'vmapops.geojson');toast('Đã xuất '+features.length+' đối tượng.');};
 let lastSearch=0;
 $('search-form').onsubmit=async e=>{e.preventDefault();const q=$('search').value.trim();const pair=q.match(/^(-?\d+(?:\.\d+)?)\s*[,;]\s*(-?\d+(?:\.\d+)?)$/);if(pair){const lat=Number(pair[1]),lon=Number(pair[2]);if(Math.abs(lat)>90||Math.abs(lon)>180){toast('Tọa độ ngoài phạm vi hợp lệ.');return;}showPlace(lat,lon,'Tọa độ đã chọn');return;}if(Date.now()-lastSearch<1100){toast('Vui lòng chờ một giây trước khi tìm tiếp.');return;}lastSearch=Date.now();const button=e.target.querySelector('button');button.disabled=true;$('search-results').textContent='Đang tìm địa điểm…';try{const res=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+encodeURIComponent(q),{signal:AbortSignal.timeout(12000),referrerPolicy:'strict-origin-when-cross-origin'});if(!res.ok)throw Error('HTTP '+res.status);const data=await res.json();$('search-results').replaceChildren();if(!data.length)$('search-results').textContent='Không tìm thấy địa điểm.';data.forEach(p=>{const b=document.createElement('button');b.textContent=p.display_name;b.onclick=()=>showPlace(Number(p.lat),Number(p.lon),p.display_name);$('search-results').append(b);});}catch{$('search-results').textContent='Không kết nối được dịch vụ tìm kiếm. Bạn vẫn có thể nhập vĩ độ, kinh độ.';}finally{button.disabled=false;}};
 function showPlace(lat,lng,name){if(searchMarker)map.removeLayer(searchMarker);const title=document.createElement('span');title.textContent=name;searchMarker=L.circleMarker([lat,lng],{radius:9,color:'#e69b38',fillOpacity:.8}).addTo(map).bindPopup(title);map.setView([lat,lng],14);searchMarker.openPopup();$('search-results').replaceChildren();if(innerWidth<800)collapse();}
 function openSettings(){$('tile-url').value=config.tileUrl||'';$('tile-credit').value=config.credit||'';$('api-url').value=config.apiUrl||'';$('api-token').value=token;$('remember').checked=!!config.token;$('api-status').textContent='';$('settings').showModal();}
 ['settings-top','api-top','api-card'].forEach(id=>$(id).onclick=openSettings);$('close-settings').onclick=()=>$('settings').close();$('show-token').onclick=()=>{const shown=$('api-token').type==='password';$('api-token').type=shown?'text':'password';$('show-token').textContent=shown?'Ẩn':'Hiện';};
 function formConfig(){return {tileUrl:url($('tile-url').value,true),credit:$('tile-credit').value.trim(),apiUrl:url($('api-url').value),token:$('api-token').value.trim()};}
 async function fetchData(c){if(!c.apiUrl)throw Error('Nhập endpoint GeoJSON trước.');const headers={Accept:'application/geo+json, application/json'};if(c.token)headers.Authorization='Bearer '+c.token;const res=await fetch(c.apiUrl,{headers,redirect:'error',credentials:'omit',signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error('API trả về HTTP '+res.status);const text=await res.text();if(text.length>20*1024*1024)throw Error('Dữ liệu API vượt 20 MB.');return validateGeoJSON(JSON.parse(text));}
 $('test-api').onclick=async()=>{const b=$('test-api');b.disabled=true;$('api-status').textContent='Đang kiểm tra…';try{await fetchData(formConfig());$('api-status').textContent='✓ Kết nối thành công, dữ liệu GeoJSON hợp lệ.';}catch(err){$('api-status').textContent='Không kết nối được: '+err.message+' Kiểm tra URL, CORS và token.';}finally{b.disabled=false;}};
 $('settings-form').onsubmit=async e=>{e.preventDefault();const submit=e.submitter;submit.disabled=true;try{const c=formConfig();let data;if(c.apiUrl){$('api-status').textContent='Đang tải dữ liệu…';data=await fetchData(c);}const persisted={tileUrl:c.tileUrl,credit:c.credit,apiUrl:c.apiUrl};if($('remember').checked)persisted.token=c.token;localStorage.setItem(KEY,JSON.stringify(persisted));sessionStorage.setItem(KEY+'.token',JSON.stringify(c.token));config=persisted;token=c.token;if(data){const g=addData(data,'Dữ liệu API riêng','api');fitGroup(g);$('connection').textContent='API đã kết nối';}else{layers.filter(x=>x.source==='api').forEach(x=>{map.removeLayer(x.group);layers.splice(layers.indexOf(x),1);});renderLayers();$('connection').textContent='Bản đồ mở';}if(c.tileUrl)setBase('custom');else if(activeBase==='custom')setBase('osm');$('settings').close();toast('Đã lưu và áp dụng cấu hình.');}catch(err){$('api-status').textContent='Chưa áp dụng: '+err.message+' Kiểm tra cấu hình và CORS.';}finally{submit.disabled=false;}};
 $('reset-settings').onclick=()=>{try{localStorage.removeItem(KEY);sessionStorage.removeItem(KEY+'.token');}catch{}config={};token='';layers.filter(x=>x.source==='api').forEach(x=>{map.removeLayer(x.group);layers.splice(layers.indexOf(x),1);});renderLayers();setBase('osm');$('connection').textContent='Bản đồ mở';$('settings').close();toast('Đã xóa cấu hình và token trên thiết bị.');};
 setBase('osm');
 const places=[['Vĩnh Long',10.253,105.972],['Cần Thơ',10.045,105.747],['TP. Hồ Chí Minh',10.776,106.701],['Mỹ Tho',10.36,106.36],['Bến Tre',10.243,106.375],['Trà Vinh',9.935,106.342]];
 const demo=addData({type:'FeatureCollection',features:places.map(([name,lat,lng])=>({type:'Feature',properties:{name,nguon:'Điểm minh họa'},geometry:{type:'Point',coordinates:[lng,lat]}}))},'Đô thị Mekong','demo');demo.eachLayer(l=>l.bindTooltip(l.feature.properties.name,{permanent:true,direction:'top',offset:[0,-8]}));
 if(config.apiUrl)$('connection').textContent='API đã lưu · chưa tải';
 // No automatic credential-bearing network request: apply explicitly in settings.
})();
